"""added contact info in company class

Revision ID: aa1b6a930823
Revises: b75a4c0d23a4
Create Date: 2019-06-23 19:41:00.522831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa1b6a930823'
down_revision = 'b75a4c0d23a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('contact_info', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'contact_info')
    # ### end Alembic commands ###
