"""added affiliates table

Revision ID: b75a4c0d23a4
Revises: e37f74c5ef98
Create Date: 2019-06-13 16:35:37.550642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b75a4c0d23a4'
down_revision = 'e37f74c5ef98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.drop_column('company', 'affiliates')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.drop_column('user', 'affiliate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('affiliate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_1', 'user', 'company', ['affiliate'], ['id'])
    op.add_column('company', sa.Column('affiliates', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('company_ibfk_1', 'company', 'user', ['affiliates'], ['id'])
    op.drop_table('affiliates')
    # ### end Alembic commands ###
