"""added company class

Revision ID: e37f74c5ef98
Revises: b944415dbb77
Create Date: 2019-06-09 14:26:55.979471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e37f74c5ef98'
down_revision = 'b944415dbb77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=254), nullable=True),
    sa.Column('logo', sa.String(length=1000), nullable=True),
    sa.Column('about_me', sa.String(length=400), nullable=True),
    sa.Column('products', sa.Integer(), nullable=True),
    sa.Column('affiliates', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affiliates'], ['user.id'], ),
    sa.ForeignKeyConstraint(['products'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    op.add_column('product', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'company', ['company_id'], ['id'])
    op.add_column('user', sa.Column('affiliate', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'company', ['affiliate'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'affiliate')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'company_id')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
