"""added primary key ot affiliates table

Revision ID: fe5cf61c79b7
Revises: aa1b6a930823
Create Date: 2019-07-04 22:03:09.243959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5cf61c79b7'
down_revision = 'aa1b6a930823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliates', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affiliates', 'id')
    # ### end Alembic commands ###
